version: "3.8"
services:
    www: 
        build: .
        ports:
            - 8085:80
        volumes:
            - ./web:/var/www/html
    db:
        image: mariadb:latest
        volumes:
          - ./init-db.d:/docker-entrypoint-initdb.d 
          - ./data:/var/lib/mysql
          - ./mycustom.cnf:/etc/mysql/conf.d/custom.cnf
        environment:
          - MYSQL_ROOT_PASSWORD=password
          - MYSQL_PASSWORD=pass123
          - MYSQL_USER=yuki
          - MYSQL_DATABASE=restaurants_db
        command: --default-authentication-plugin=mysql_native_password
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8086:80
        environment:
            MYSQL_USER: yuki
            MYSQL_PASSWORD: pass123
            MYSQL_ROOT_PASSWORD: password 
